from enum import StrEnum


class GlobalRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    PLATFORM_ADMIN = "PLATFORM_ADMIN"
    VERIFICATION_ADMIN = "VERIFICATION_ADMIN"
    MODERATOR = "MODERATOR"
    FINANCE_ADMIN = "FINANCE_ADMIN"
    ELECTION_ADMIN = "ELECTION_ADMIN"
    ALUMNI_MEMBER = "ALUMNI_MEMBER"
    UNVERIFIED_USER = "UNVERIFIED_USER"

